trigger:
- main

pool:
  name: Default

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore
  displayName: Restore

- script: dotnet build --configuration Release
  displayName: Build

- script: dotnet pack --configuration Release -o $(Build.ArtifactStagingDirectory)
  displayName: Pack NuGet

- script: dotnet nuget push "$(Build.ArtifactStagingDirectory)/*.nupkg" --source "stringextensions-feed" --api-key az --skip-duplicate
  displayName: Push to Azure Artifacts